"""Inicializar migración

Revision ID: 0c77f715fc0a
Revises: 
Create Date: 2023-10-04 17:49:15.807080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c77f715fc0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.alter_column('author',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('author',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
