"""empty message

Revision ID: 3e7813f71ab6
Revises: 5eb9077ddad1
Create Date: 2023-10-04 17:56:15.081797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e7813f71ab6'
down_revision = '5eb9077ddad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coments', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_constraint('coments_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coments', schema=None) as batch_op:
        batch_op.create_foreign_key('coments_ibfk_1', 'users', ['author'], ['id'])
        batch_op.alter_column('author',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
